### ISSUE TITLE
Error executing plugins.sh in Windows

### ISSUE THREAD

**Issue by restalion** [Accenture/adop-jenkins#15]
Running docker build in Windows I found an error when plugins.sh is executed:

`the command returned a non-zero code 3`

If I run the same command in OSX it ends without errors, it seems to be some kind of problem with plugins.txt file.

**Comment by RobertNorthard** [comment]
Thanks @restalion for this. This error is due to windows line ending. 

To prevent line feeds being converted to CRLF on checkout on windows I suggest you update your global git config: 
`git config --global core.autocrlf false`
