### ISSUE TITLE
Load_Platform fail

### ISSUE THREAD

**Issue by dcuenot** [Accenture/adop-jenkins#2]
Hello,

I used ./setup-local.sh in order to configure my ADOP stack.
The creation is OK, but when I start the Load_Platform job, I get this issue:

> 10:57:11 + echo 'Repository already exists, skipping: platform-management'
> 10:57:11 Repository already exists, skipping: platform-management
> 10:57:11 + git remote add adop ssh://jenkins@gerrit:29418/platform-management
> 10:57:11 + git fetch adop
> 10:57:12 + git push adop '+refs/remotes/origin/_:refs/heads/_'
> 10:57:12 fatal: internal server error
> 10:57:12 fatal: Could not read from remote repository.
> 10:57:12 
> 10:57:12 Please make sure you have the correct access rights
> 10:57:12 and the repository exists.
> 10:57:12 Build step 'Execute shell' marked build as failure
> 10:57:12 [ssh-agent] Stopped.
> 10:57:12 Finished: FAILURE

I did a docker exec inside Jenkins container, I started manually a git clone, and it seems that there is a RSA key issue:

> root@79bcc2fc0b82:/tmp# git clone ssh://jenkins@gerrit:29418/platform-management
> Cloning into 'platform-management'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Do you know how to fix it?
Thanks in advance!

**Comment by RobertNorthard** [comment]
@dcuenot is this a vanilla ADOP stack? If this has been resolved please can you close this issue?

**Comment by RobertNorthard** [comment]
@dcuenot I'm closing this issue as there was no response.
