### ISSUE TITLE
Jenkins 2.73.3 LTS upgrade

### ISSUE THREAD

**Issue by anton-kasperovich** [Accenture/adop-jenkins#48]
This issue is created to raise awareness that I'm working on upgrade of Jenkins from 2.7.4 LTS to 2.73.3 LTS. I'll create separate "v2 branch" in the repository and create a PR to make progress more visible. There are quite many issues to work with i.e. almost all plugins should be updated and I expect some rework on init groovy scripts as well:

![screencapture-51-15-36-244-jenkins-1507969134521](https://user-images.githubusercontent.com/380055/31659532-3127d214-b33d-11e7-80d8-48a738d5883c.png)

**Comment by nickdgriffin** [comment]
Yikes! Good luck!

We can use a release candidate tag to make it easier to work with I think.

**Comment by svscorp** [comment]
@anton-kasperovich Hi Anton,

You were just a bit earlier :) I am busy with same (meanwhile testing the setup on-premise as well): https://github.com/svscorp/adop-jenkins/tree/jenkins-2.73.1 

It's fine and cool, we can cooperate?

Would you mind me making the first PR with current progress on https://github.com/svscorp/adop-jenkins/tree/jenkins-2.73.1? Then you can develop further from it. Please, have a look and let me know.

I've also tried around 20 installations with this image and figured out which plugins can be updated with still making platform-management work as is.

Anyways, let's cooperate.

**Comment by bzon** [comment]
@anton-kasperovich  I'd recommend using the [latest plugins shell script](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh) included in the base docker image for installing plugins. It made my life easier a lot. 

For the plugins text file list, you just have to append `:latest` and it will install the `latest compatible version` of the plugin according to the Jenkins version that you are using. 

```bash
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins-latest.txt
```
See our fork here https://github.com/pdcbuckets/adop-jenkins-gitlab-integration

You may also consider installing `permissive-script-security`.  System groovy scripts will not work naturally anymore and there will be a lot to approve.  See this for reference http://blog.ehrnhoefer.com/2017-04-23-jenkins-groovy-security/

**Comment by nickdgriffin** [comment]
"latest" is fine for a one time install to make the upgrade easier but we can't have it in the "plugins.txt" inside the image that is published, plugin version changes can have a big effect on dependent items and I'd rather we didn't have the potential for uncontrolled change creeping in each time the image is built please.

Great example is Job DSL, when that changes significantly it impacts all of the cartridges and can potentially break them (e.g. when "workflow" became "pipeline" in the syntax).

**Comment by SvenClauw** [comment]
One idea is to use the :latest field one time and use the versions shown in the docker logs when the image is created. This will save a lot of time figuring all dependencies :)

**Comment by anton-kasperovich** [comment]
Last time I've done this, upgraded plugins from Jenkins UI and just via groovy script exported list of plugins with versions. In this case Jenkins knows better what is compatible and what is not https://stackoverflow.com/a/35292719 .

I'm definitely taking your suggestions, very helpful, thanks!

**Comment by avoidik** [comment]
I'd like to link this here https://github.com/Accenture/adop-platform-management/issues/48

**Comment by avoidik** [comment]
Also I'd like to note that upgrade will solve the OOM-Killer issue with Java JRE/JDK upgrade (which has been included in the upstream docker image for Jenkins)

https://blog.csanchez.org/2017/05/31/running-a-jvm-in-a-container-without-getting-killed/

**Comment by anton-kasperovich** [comment]
Linking plat-man PR https://github.com/Accenture/adop-platform-management/pull/53 and Jenkins PR https://github.com/Accenture/adop-jenkins/pull/52. I'm checking plugins now.

**Comment by RobertNorthard** [comment]
Hi @anton-kasperovich, I have created PR https://github.com/Accenture/adop-jenkins/pull/54 that includes the Jenkins upgrade and plugins.

**Comment by RobertNorthard** [comment]
Closing as Jenkins has been upgraded to 2.107.3 LTS.
